# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('nascimento', models.CharField(max_length=10, verbose_name=b'nascimento')),
                ('mae', models.CharField(max_length=100, verbose_name=b'mae')),
                ('pai', models.CharField(max_length=100, verbose_name=b'pai')),
                ('CPF', models.CharField(max_length=11, verbose_name=b'CPF')),
                ('RG', models.CharField(max_length=10, verbose_name=b'RG')),
                ('orgao_emissor', models.CharField(max_length=10, verbose_name=b'orgao_emissor')),
                ('local', models.CharField(max_length=2, verbose_name=b'local')),
                ('email', models.CharField(max_length=50, verbose_name=b'email')),
                ('matricula', models.CharField(max_length=15, verbose_name=b'matricula')),
                ('turma', models.CharField(max_length=10, verbose_name=b'turma')),
                ('turno', models.CharField(max_length=15, verbose_name=b'turno')),
                ('ano_de_conclusao', models.IntegerField()),
                ('telefone', models.CharField(max_length=20, verbose_name=b'telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name=b'endereco')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('CNH', models.CharField(max_length=2, verbose_name=b'CNH')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name=b'nome')),
                ('coordenador', models.CharField(max_length=100, verbose_name=b'coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name=b'nome')),
                ('atividade', models.CharField(max_length=30, verbose_name=b'atividade')),
                ('CNPJ', models.CharField(max_length=18, verbose_name=b'CNPJ')),
                ('area_de_atuacao', models.CharField(max_length=50, verbose_name=b'area_de_atuacao')),
                ('endereco', models.CharField(max_length=100, verbose_name=b'endereco')),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('telefone', models.CharField(max_length=20, verbose_name=b'telefone')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_inicial', models.CharField(max_length=5, verbose_name=b'hr_inicial')),
                ('hr_final', models.CharField(max_length=5, verbose_name=b'hr_final')),
                ('dia_inicio', models.CharField(max_length=10, verbose_name=b'dia_inicio')),
                ('dia_fim', models.CharField(max_length=10, verbose_name=b'dia_fim')),
                ('duracao_minima', models.CharField(max_length=10, verbose_name=b'duracao_minima')),
                ('responsavel', models.CharField(max_length=100, verbose_name=b'responsavel')),
                ('funcao', models.CharField(max_length=30, verbose_name=b'funcao')),
                ('local_do_estagio', models.CharField(max_length=30, verbose_name=b'local_do_estagio')),
                ('regime_trabalho', models.CharField(max_length=1, verbose_name=b'regime_trabalho')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='blog.Aluno', verbose_name=b'Aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Acompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Acompanhamento', to='blog.Aluno', verbose_name=b'Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Acompanhamento', to='blog.Curso', verbose_name=b'Curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Acompanhamento', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Avaliacao_Discente_Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Discente_Estagio', to='blog.Aluno', verbose_name=b'Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Discente_Estagio', to='blog.Curso', verbose_name=b'Curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Discente_Estagio', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Avaliacao_Estagio_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Estagio_Empresa', to='blog.Aluno', verbose_name=b'Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Estagio_Empresa', to='blog.Curso', verbose_name=b'Curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Avaliacao_Estagio_Empresa', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Inscricao', to='blog.Aluno', verbose_name=b'Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Inscricao', to='blog.Curso', verbose_name=b'Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Plano_Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plano_Estagio', to='blog.Aluno', verbose_name=b'Aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plano_Estagio', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('matricula', models.CharField(max_length=15, verbose_name=b'matricula')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('CPF', models.CharField(max_length=11, verbose_name=b'CPF')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
                ('endereco', models.CharField(max_length=50, verbose_name=b'endereco')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('CREA', models.CharField(max_length=10, verbose_name=b'CREA')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='plano_estagio',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plano_Estagio', to='blog.Professor', verbose_name=b'Professor'),
        ),
        migrations.AddField(
            model_name='ficha_acompanhamento',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ficha_Acompanhamento', to='blog.Professor', verbose_name=b'Professor'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='blog.Professor', verbose_name=b'Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to='blog.Curso', verbose_name=b'Curso'),
        ),
    ]
