# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('CPF', models.CharField(max_length=11, verbose_name=b'CPF')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
                ('endereco', models.CharField(max_length=50, verbose_name=b'endereco')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('CREA', models.CharField(max_length=10, verbose_name=b'CREA')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='blog.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.RenameModel(
            old_name='Professor',
            new_name='Orientador',
        ),
        migrations.RemoveField(
            model_name='ficha_acompanhamento',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ficha_acompanhamento',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ficha_acompanhamento',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ficha_acompanhamento',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_discente_estagio',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_discente_estagio',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_discente_estagio',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_estagio_empresa',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_estagio_empresa',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='ficha_avaliacao_estagio_empresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ficha_inscricao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ficha_inscricao',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='plano_estagio',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='plano_estagio',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='plano_estagio',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='estagio',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='estagio',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='blog.Orientador', verbose_name=b'Orientador'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ficha_Acompanhamento',
        ),
        migrations.DeleteModel(
            name='Ficha_Avaliacao_Discente_Estagio',
        ),
        migrations.DeleteModel(
            name='Ficha_Avaliacao_Estagio_Empresa',
        ),
        migrations.DeleteModel(
            name='Ficha_Inscricao',
        ),
        migrations.DeleteModel(
            name='Plano_Estagio',
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
        migrations.AddField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='blog.Supervisor', verbose_name=b'Supervisor'),
            preserve_default=False,
        ),
    ]
