# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('nascimento', models.CharField(max_length=10, verbose_name=b'nascimento')),
                ('mae', models.CharField(max_length=100, verbose_name=b'mae')),
                ('pai', models.CharField(max_length=100, verbose_name=b'pai')),
                ('CPF', models.CharField(max_length=11, verbose_name=b'CPF')),
                ('RG', models.CharField(max_length=10, verbose_name=b'RG')),
                ('orgao_emissor', models.CharField(max_length=10, verbose_name=b'orgao_emissor')),
                ('local', models.CharField(max_length=2, verbose_name=b'local')),
                ('email', models.CharField(max_length=50, verbose_name=b'email')),
                ('matricula', models.CharField(max_length=15, verbose_name=b'matricula')),
                ('turma', models.CharField(max_length=10, verbose_name=b'turma')),
                ('turno', models.CharField(max_length=15, verbose_name=b'turno')),
                ('ano_de_conclusao', models.IntegerField()),
                ('telefone', models.CharField(max_length=20, verbose_name=b'telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name=b'endereco')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('CNH', models.CharField(blank=True, max_length=2, null=True, verbose_name=b'CNH')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name=b'nome')),
                ('coordenador', models.CharField(max_length=100, verbose_name=b'coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name=b'nome')),
                ('funcao_mercado_de_trabalho', models.CharField(max_length=50, verbose_name=b'funcao_mercado_de_trabalho')),
                ('nome_responsavel', models.CharField(max_length=100, verbose_name=b'nome_responsavel')),
                ('atividade', models.CharField(max_length=30, verbose_name=b'atividade')),
                ('CPF_responsavel', models.CharField(max_length=11, verbose_name=b'CPF_responsavel')),
                ('email_supervisor', models.CharField(max_length=30, verbose_name=b'email_supervisor')),
                ('CNPJ', models.CharField(max_length=18, verbose_name=b'CNPJ')),
                ('area_de_atuacao', models.CharField(max_length=50, verbose_name=b'area_de_atuacao')),
                ('endereco', models.CharField(max_length=100, verbose_name=b'endereco')),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('telefone', models.CharField(max_length=20, verbose_name=b'telefone')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_inicial', models.CharField(max_length=5, verbose_name=b'hr_inicial')),
                ('hr_final', models.CharField(max_length=5, verbose_name=b'hr_final')),
                ('periodo_semanal', models.CharField(max_length=30, verbose_name=b'periodo_semanal')),
                ('dia_inicio', models.CharField(max_length=10, verbose_name=b'dia_inicio')),
                ('dia_fim', models.CharField(max_length=10, verbose_name=b'dia_fim')),
                ('duracao_minima', models.CharField(max_length=10, verbose_name=b'duracao_minima')),
                ('funcao', models.CharField(max_length=30, verbose_name=b'funcao')),
                ('local_do_estagio', models.CharField(max_length=30, verbose_name=b'local_do_estagio')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Aluno', verbose_name=b'Aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('matricula', models.CharField(max_length=15, verbose_name=b'matricula')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('CPF', models.CharField(max_length=11, verbose_name=b'CPF')),
                ('email', models.CharField(max_length=30, verbose_name=b'email')),
                ('endereco', models.CharField(max_length=50, verbose_name=b'endereco')),
                ('bairro', models.CharField(max_length=50, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name=b'cidade')),
                ('UF', models.CharField(max_length=2, verbose_name=b'UF')),
                ('CEP', models.CharField(max_length=10, verbose_name=b'CEP')),
                ('CREA', models.CharField(max_length=10, verbose_name=b'CREA')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='app.Empresa', verbose_name=b'Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Orientador', verbose_name=b'Orientador'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Supervisor', verbose_name=b'Supervisor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to='app.Curso', verbose_name=b'Curso'),
        ),
    ]
