# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Curso', verbose_name=b'Curso'),
            preserve_default=False,
        ),
    ]
