# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estagio_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo1', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo2', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo3', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo4', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo5', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo6', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
                ('modelo7', models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados')),
            ],
        ),
    ]
