# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:21
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fichas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='fichas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Estagio', to='app.Fichas', verbose_name=app.models.Fichas),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichas',
            name='modelo8',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name=b'modelo de certificados'),
        ),
    ]
